import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format } from 'prettier';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const source = resolve(root, 'skills/pilot/SKILL.md');
const output = resolve(root, 'src/cli/skill-template.ts');
const content = await readFile(source, 'utf8');

if (!content.startsWith('---\n') || !content.includes('\nname: pilot\n')) {
  throw new Error(`${source} is missing valid Pilot skill frontmatter`);
}

const generated = await format(
  `// Generated by scripts/build-skill.mjs from skills/pilot/SKILL.md.\n// Do not edit this file directly.\nexport const SKILL_CONTENT = ${JSON.stringify(content)};\n`,
  { parser: 'typescript', singleQuote: true }
);

await mkdir(dirname(output), { recursive: true });
await writeFile(output, generated, 'utf8');
